### ISSUE TITLE
Raspbian Jessie: Half successful installation 

### ISSUE THREAD

**Issue by akiratwang** [pi-top/pi-topPULSE#26]
Hi, I'm running the latest build of raspbian Jessie and have done multiple fresh install and updates before attempting to install pt-pulse. I've never had trouble getting the speaker to work (aplay -l) but the microphone nor LED work at all (arecord -l). O have attempted manual installations with the speaker always working but not the microphone or LED. My current installation steps are:
1) fresh install of raspbian Jesse
2) Sudo apt upgrade
3) Sudo apt install pt-pulse
4) enable I2C and serial through terminal as stated in manual installations
5) aplay -l which successfully shows the pitop soundcard
6) arecord -l which displays nothing

**Comment by rricharz** [comment]
Do you really mean Jessie, not Stretch? With the latest Stretch it should work properly. Also, before doing the sudo apt upgrade, you need to do a sudo apt update. Otherwise you are not getting the latest updates. Before doing the sudo apt install pt-pulse I propose to install sudo apt install pt-hub.

**Comment by akiratwang** [comment]
Ok I shall try that (I just realised stretch was released last Nov and I was just using Jessie from early 2017). Thanks :)

**Comment by rricharz** [comment]
If you want, you can follow this guide: https://github.com/rricharz/pi-top-setup

**Comment by m-roberts** [comment]
The microphone runs over UART (serial), and so will not show under `arecord -l`. Have you run the [microphone test script](https://github.com/pi-top/pi-topPULSE/blob/master/examples/mic-demo.py) and tested playing back the generated audio files?

As for the LEDs, have you run the [LED test script](https://github.com/pi-top/pi-topPULSE/blob/master/examples/led-demo.py) and checked for the output?

**Comment by akiratwang** [comment]
Im currently following rricharz's method on his git. Also, is there a way to then use the microphone with google assistant (the main reason why i need the ptpulse). Google suggests using the ALSA soundcard

**Comment by m-roberts** [comment]
Unfortunately, I do not know if there is a way to use the pi-topPULSE's microphone with anything that is specifically dependent on ALSA microphone input.

**Comment by akiratwang** [comment]
Ok so I have go the sound and LED lights all working. The microphone DOES work using the test script. I found something called ttymidi but it is now years old which allowed UART serial to be used with ALSA. For now it seems I may need to buy usb mic. Thanks for everything!

**Comment by m-roberts** [comment]
No problem - thank you for pointing out ttymidi as a possible solution to this problem, though!

Are you happy to close this issue?
