### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by marcstringer** [pi-top/pi-topPULSE#33]
Using a Pi-top Pulse PULSE running into the following error.
Tried these instrucitons aswell but it failed also. 
https://github.com/rricharz/pi-top-setup/issues

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pt-pulse : Depends: pt-device-manager (>= 1.0.1) but it is not installable
            Recommends: mpg123
E: Unable to correct problems, you have held broken packages.

**Comment by m-roberts** [comment]
Try `sudo apt install -y mpg123` and then try again.
