### ISSUE TITLE
Bluetooth stops working after device has been connected

### ISSUE THREAD

**Issue by benp44** [pi-top/pi-topPULSE#4]
**NOTE: The modifications that are causing this break are only required by Raspbian Jessie (not Raspbian Stretch)**
*These steps can simply be removed when migrating to Stretch*

Audio data from the microphone is captured and LED data is sent over the Raspberry Pi serial ports. This data is sent and received at a custom baud rate of 250KHz, hence the serial port baud rate is set via `/boot/config.txt`:

```
enable_uart=1
init_uart_clock=1627604
init_uart_baud=460800
```

Although these settings are documented as only affecting the secondary, mini uart port, they seem to disable Bluetooth.

After the pi-topPULSE is disconnected, these settings are not restored to their defaults, so the pi-topPULSE can be reconnected and used without rebooting.

**Workaround**

For the time being, it is possible to restore Bluetooth functionality after using a pi-topPULSE by manually commenting out these settings in `/boot/config.txt`.

1. Disconnect the pi-topPULSE. If a pi-topPULSE is connected, serial device settings will be restored automatically.

2. In a terminal window run the following:
`sudo leafpad /boot/config.txt`

3. Find the following lines:

```
init_uart_clock=1627604
init_uart_baud=460800
```

4. Comment them out by adding a **#** symbol in front of each:
```
#init_uart_clock=1627604
#init_uart_baud=460800
```

5. Save the file
6. Reboot your Pi

**Comment by m-roberts** [comment]
Closing this, as this no longer happens on Stretch.
